### ISSUE TITLE
Trafo : What should be the new bin boundary value to enter manually (how to consider the value ?)

### ISSUE THREAD

**Issue by snborah** [spex-xray/spex-help#13]
Learning to use SPEX. I was using "trafo' to convert spectra in OGIP formate to SPEX formate. On entering the name of the response matrix file, I got the message like this,

"Enter filename response matrix to be read: M1_rmf.rmf
 Reading response matrix ...
 Lower model bin boundary for bin        1 must be positive; current values:   0.000000E+00  5.000000E-03
 Enter new bin boundary values manually:"

What minimum value should be entered. I got that it must be positive. I tried with 1 , 0.1. But no result was found after waiting for time.
Please give me some idea.

**Comment by jdeplaa** [comment]
Any number that is smaller than 5.0E-3 and larger than 0 is fine. Usually, I put 3E-5 there.

For some instruments (e.g. EPIC MOS on XMM), the lowest energy bin boundary is 0, which is actually unphysical, because photons with 0 energy do not exist. Hence, SPEX wants to correct this. Since this first bin is usually ignored in a spectral analysis, it does not matter a lot what is being filled out here, as long as it is smaller than the upper bin boundary and not 0.

**Comment by snborah** [comment]
Thanks for valuable suggestion. I am using your value, it is taking time
(for reading response matrix) after I put 3E-5.      Regards,
SN Borah.
