### ISSUE TITLE
Standard abundance set from Lodders et al. (2009)

### ISSUE THREAD

**Issue by RebecaMelo** [spex-xray/spex-help#15]
Dear SPEX Team,

I was looking at the solar table values in Table 4 from [Lodders et al. (2009)](https://ui.adsabs.harvard.edu/abs/2009LanB...4B..712L/abstract) (abundance default) when I noticed a difference between the values on that paper and Spex values [here](https://spex-xray.github.io/spex-help/reference/commands/abundance.html?highlight=lodders) or in the [manual](https://zenodo.org/record/4384188/files/spex-3.06.01-Manual.pdf?download=1).

Could you please explain to me why these values are different? What am I missing?

Thank you,
Rebeca Batalha

**Comment by jdeplaa** [comment]
Dear Rebeca,

In SPEX, we use by default proto-solar abundances, which are supposed to be closer to the composition of the ISM than the solar photosphere. In X-ray analysis, we are usually interested in abundances on larger scales than our own sun, which is why we chose this set to be default.

In Lodders (2009), the proto-solar values are listed in Table 10 (abundances 4.5 Gyr ago). However, in this table the abundances are normalised on Silicon, while in SPEX we normalise everything to Hydrogen. The Lodders (2009) values from Table 10 are therefore renormalised to H and those are the values listed in the SPEX manual (and used in SPEX). This is why the numbers from the Lodders paper do not correspond one-to-one to the SPEX manual.

For example, if we renormalise Si to H (Si/H with respect to 1E+12 H atoms):
```
Si/H = log((1E+6/2.59E+10) * 1E+12) = log(3.86E+7) = 7.586
```
So taking 1E+6 for Si and 2.59E+10 for H from Table 10 becomes 7.586 for Si in the abundance table in the manual.

I hope this clarifies the difference.

**Comment by RebecaMelo** [comment]
Dear Jelle De Plaa,

Yes, it's clear. Thank you for your quick reply and the explanation.

Best regards,

**Comment by krutkow** [comment]
Thanks for the clarification on the numbers.

In another table, for Anders and Grevesse 1989, it seems you use table 2 from that paper, which lists the photospheric abundances. It looks like there is a typo for Scandium, it should be 3.10, not 1.10.
