### ISSUE TITLE
Error when Install the SPEX Python interface

### ISSUE THREAD

**Issue by jmao2014** [spex-xray/spex-help#18]
Hi @jdeplaa 

I tried to install the SPEX python interface and failed. You can find some info below. Please let me know how to proceed. Thanks!

OS system:  Ubuntu 20.04.3 LTS
SPEX version: 3.06.01
python version: 3.8.8
conda version: 4.10.3

The following is the error message: 

(base) junjie@congguan:~/pkg/spex/SPEX-3.06.01-Linux/python$ conda env create -f $SPEX90/python/spex.yml
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Installing pip dependencies: \ Ran pip subprocess with arguments:
['/home/junjie/anaconda3/envs/spex/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/junjie/pkg/spex/SPEX-3.06.01-Linux/python/condaenv.ix09mb5_.requirements.txt']
Pip subprocess output:

Pip subprocess error:
Traceback (most recent call last):
  File "/home/junjie/anaconda3/envs/spex/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/junjie/anaconda3/envs/spex/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/junjie/anaconda3/lib/python3.8/site-packages/pip/__main__.py", line 21, in <module>
    from pip._internal.cli.main import main as _main
  File "/home/junjie/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
                                                                                                                                                 failed

CondaEnvException: Pip failed

**Comment by jdeplaa** [comment]
Hi @jmao2014 

Hmm, this appears to be a problem with your installation of 'pip'. Pip is only used to install ``pyspextools``, so you could try the following to work around the problem:
```
(base) linux:~> conda create -n spex python=3.5  numpy=1.15 future matplotlib sphinx astropy scipy jupyter_client ipykernel
(base) linux:~> conda activate spex
(spex) linux:~> conda install pip
(spex) linux:~> pip install pyspextools
```
From your error message, it appears that the spex conda environment already exists. Maybe the first command above will complain about that. After activating the environment, it should re-install pip and then install pyspextools. 

If the problem is in the version of pip, then the last ``pip install`` command will fail. In that case, pyspex will work in this environment, but not pyspextools. Could you tell me the version of pip if this happens?

**Comment by jmao2014** [comment]
@jdeplaa 

Pip version for the base python env: 
`pip 21.0.1 from /home/junjie/anaconda3/lib/python3.8/site-packages/pip (python 3.8)
`

SPEX conda environment exists even if it ran into errors. 

After activating the spex python env: 
```
(spex) junjie@congguan:~/pkg/spex/SPEX-3.06.01-Linux/python$ conda install pip
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(spex) junjie@congguan:~/pkg/spex/SPEX-3.06.01-Linux/python$ pip --version
Traceback (most recent call last):
  File "/home/junjie/anaconda3/envs/spex/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/junjie/anaconda3/lib/python3.8/site-packages/pip/_internal/__init__.py", line 15, in main
    from pip._internal.utils.entrypoints import _wrapper
  File "/home/junjie/anaconda3/lib/python3.8/site-packages/pip/_internal/utils/entrypoints.py", line 3, in <module>
    from pip._internal.cli.main import main
  File "/home/junjie/anaconda3/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
```

Run "pip install pyspextools" will have the same error.

**Comment by jdeplaa** [comment]
The issue is probably that python 3.5 is already quite old, and I am a bit curious why your install takes pip from python 3.8. In my conda spex environment, it installs pip 10.0.1, which still has a python 3.5 install file. Maybe it is worth trying to force pip to downgrade **inside** the spex environment:
```
conda install pip=10.0.1
```
On my machine this version of pip works in a python 3.5 conda environment (it just complains there is a newer pip version). Clearly, the next spex version should use a higher python version, since 3.5 is apparently becoming obsolete.

If the downgrading does not work, maybe upgrading pip using pip is another idea to get a different version:
```
pip install --upgrade pip
```

If all else fails, maybe remove the spex conda environment and start over:
```
conda remove --name spex --all
```

**Comment by jmao2014** [comment]
Hi @jdeplaa, 

- I am a bit curious why your install takes pip from python 3.8
> I think I know the answer to this when you pointed out. In my ~/.bashrc file, I pointed PYTHONPATH to python 3.8. Once I remove it, it is no longer looking for python 3.8. But I also specified python version when creating the python environment

`conda env create -f $SPEX90/python/spex.yml python=3.5.0
`

It succeeded (no error messages). But, no module named pyspex ... 

(spex) junjie@congguan:/stage1/junjie/astro$ python
Python 3.5.6 |Anaconda, Inc.| (default, Aug 26 2018, 21:41:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyspex.spex import Session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'pyspex'
>>> quit()

It would work if I set the PYTHONPATH again (but to spex): 

`export PYTHONPATH=/home/junjie/anaconda3/envs/spex/lib/python3.5/site-packages
`

I guess I can write a local shell script to initialize this ... 

Cheers,

Junjie

**Comment by jdeplaa** [comment]
The pyspex module is part of the SPEX install. If you source spex inside the spex conda environment using:
```
(spex) linux:~> source /opt/spex/spexdist.sh 
```
(you may need to change the spex install path to your local choice), then $SPEX90/python will be added to your PYTHONPATH variable and pyspex should be available within python.

**Comment by jmao2014** [comment]
I see. I sourced spexdist.sh outside the spex python env first and did not source it again.
