### ISSUE TITLE
Error during SPEX installation in Ubuntu 20

### ISSUE THREAD

**Issue by Anuvab759** [spex-xray/spex-help#19]
Sir/ma'am,

I am attempting to install the latest version of SPEX in my Ubuntu 20, but as I am trying to load spex, it is flashing the following error message:

**spex: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory**

All I have done so far is as follows:

1: I have downloaded the latest version of spex from the web.

2: untar:  tar xvfz spex-3.06.01-Linux-x86_64.tar.gz

3: export SPEX90=/home/anuvab/Downloads/SPEX-3.06.01-Linux

4: source $SPEX90/spexdist.sh

After this, I am trying to load spex, but I am getting the previously mentioned error message.

Could you kindly let me know how to get around this issue?

Thanks in advance.

regards,
Anuvab Banerjee
S N Bose National Centre for Basic Sciences,
Kolkata, India

**Comment by jdeplaa** [comment]
Dear Anuvab,

This error happens because libncurses version 5 was not (yet) installed on your ubuntu installation. If you are using Ubuntu 20.04 LTS, this can be done easily by giving the command:

`sudo apt-get install libncurses5`

The steps that you took look good! After installing the package above, spex should run normally. It could be that also libtinfo.so.5 is not available. If so, this can be installed with the command `sudo apt-get install libtinfo5`. Once these libraries are installed, it should work fine.

**Comment by Anuvab759** [comment]
Prof. De Plaa,

Thank you so much for the response. It has now worked perfectly.

regards,
Anuvab
