### ISSUE TITLE
Plot adum with pyspex

### ISSUE THREAD

**Issue by suasapienza** [spex-xray/spex-help#23]
Hello,

I am trying to dump on an ASCII file a simulated spectrum with pyspex. 
Unfortunately, I did not find any command on the manual that resemble the "plot adum" command that can be easily executed with SPEX. 
It is actually possible to dump a spectrum on an ASCII file with the python version of SPEX?

Thank you in advance
Vincenzo Sapienza

**Comment by jdeplaa** [comment]
Hi Vincenzo,

Thanks for asking this question! The `plot adum` command was not copied into pyspex, because we had the idea that the plot data would be available in the Python object that you get. Maybe we were wrong to omit this. 

I have to warn that there is an annoying bug in the pyspex plotting part that reads the numbers from SPEX in the background. This may give the wrong Y axis scale. Therefore, the safest would be to use the original SPEX plot routines to dump them to file.
```
s.command("plot dev null")
s.command("plot type data")
s.command("plot")
s.command("plot adum test overwrite")
```
This will output a QDP file directly that you can plot with the qdp program in HEASOFT. 

The plot bug will be fixed in the upcoming 3.07 SPEX version that we hope to release before the summer.
