### ISSUE TITLE
Bins with zero counts

### ISSUE THREAD

**Issue by mguainazzi** [spex-xray/spex-help#25]
Dear Jelle^2,

 I have been looking for a description on how spectral channels with 0 counts are treated in SPEX [apologies if this is explained somewhere in the documentation and I missed that]. 

 The reason why I am asking is that I am trying to analyze a Chandra/ACIS spectrum of a very weak AGN, using Kaastra & Bleeker (2016) "optimal rebinning technique". The spectral bins with zero counts do not seem to be displayed by "plot" (no data point, no error bar) - what does not seem right to me.

 Thanks, Matteo

**Comment by jdeplaa** [comment]
Not seeing bins with zero counts in the plots is due to the way you plot the spectrum (with the pgplot package).

With 0 counts, the Poissonian error is also zero, so the length of the plotted error bar is zero. To see that there are still data in the plot, you may for instance try to add a plot symbol, like the following commands:

```
plot set all
plot data sym 17
plot data di true
``` 

This will plot filled circles (pgplot symbol 17) at the location of the datapoints, and you will see the data. 

For the spectral fitting, when using the recommended c-stat: when both the data and the model for a bin are zero, then we add zero to the total c-stat, its expectation and variance (there is no information contained in data and model). When either data or model is non-zero, we compute the appropriate contribution.
