### ISSUE TITLE
Hydro Driver: PATH?

### ISSUE THREAD

**Issue by rjfarber** [spex-xray/spex-help#27]
In https://spex-xray.github.io/spex-help/tools/hydro_driver.html#sect-hydrodriver, it says hydro_driver is available in the SPEX distribution. I can't seem to find it. What is the path and name exactly?

**Comment by jdeplaa** [comment]
Yes, I see the problem. The `hydro_driver.f90` file is not there. Thank you for reporting! Unfortunately, I do not have a quick solution, because I do not have the file either. I do not think the `hyd` model has been used in the last 15 years... I have a colleague who should have it, but he is unavailable for the coming weeks. I will see what I can do to retrieve the file.

**Comment by jdeplaa** [comment]
We have retrieved the hydro_driver.f90 program and uploaded it in commit 96a57a8. You can now download the file on the documentation pages (both [tools/hydro_driver](https://spex-xray.github.io/spex-help/tools/hydro_driver.html) and [models/hyd](https://spex-xray.github.io/spex-help/models/hyd.html). Let us know if you have any questions.
