### ISSUE TITLE
How to use the response files of other instruments when simulating the spectra？

### ISSUE THREAD

**Issue by TaoWu666** [spex-xray/spex-help#38]
Hi Jelle,

I have another problem, asking for your help. After modeling the XMM-Newton/RGS spectrum, I plan to use the 'simulate' command to simulate the data according to the existing model, but I want to use the response file of other instruments (such as HUBS). Is there any method?

Cheers,

Tao.

**Comment by jdeplaa** [comment]
Yes, there is. Make sure that you save the parameters of your RGS model to a `.com` file. You can do that using the `par write` command in SPEX. For example: `par write xmm_rgs`. This will create a text file called `xmm_rgs.com` containing all the `par` commands to set the model to its original state. Also make sure that you have a `.com` file with the model set-up (list of components in the right order). There is no command for that, unfortunately.

## Create spo and res files for HUBS

To simulate for a different instrument, you need a spectrum and response file in SPEX format. The problem is usually that new missions do not provide a spectrum to use in trafo. For this case, there is the [simres](https://spex-xray.github.io/pyspextools/tutorials/simres.html) command in [pyspextools](https://spex-xray.github.io/pyspextools/install.html). Follow the links for use and install instructions.

The `simres` command reads in the rmf and arf (or rsp) from the new mission and creates a dummy spectrum. The output is a set of spo and res files.

## Simulate the spectrum

Once you have the HUBS spo and res file, load them into SPEX using the `data` command. Then re-create the model setup with the exact components and order that you had before. Once the model setup is exactly the same, you can run the output file from the `par write` command: `log exe xmm_rgs`. Run `calc` to calculate the model. Also create a data plot to see whether the model shows up correctly (mind the distance setting as well). 

When the model looks fine (the data are nonsense at this point), simulate the HUBS spectrum with the command `simulate 100000` for a 100 ks exposure time. You can of course vary the exposure time as you like. The dummy spectrum should be replaced by a nice simulation after giving the simulate command.

Let me know if you have questions.

**Comment by TaoWu666** [comment]
Hi Jelle,

The approach that you have provided is very successful. Thanks for your help!

Cheers,

Tao.
